In [1]:
'''1. What is a Python library? Why do we use Python libraries?   '''

# ans 

# A Python library is a collection of pre-written code that allows you to perform common programming tasks without having to write the code from scratch. These libraries consist of modules, which are files containing Python code (functions, classes, and variables) that can be reused in other programs.

'1. What is a Python library? Why do we use Python libraries?   '

In [2]:
# 2. What is the difference between Numpy array and List?

# ans

'''Python List:
Definition: A built-in Python data structure that can hold a collection of items of different types.
Flexibility: Lists can contain different data types, such as integers, strings, and other objects.
NumPy Array:
Definition: A powerful, multidimensional array object provided by the NumPy library, designed for numerical computations.
Homogeneity: NumPy arrays are homogeneous, meaning all elements must be of the same type (e.g., all integers or all floats).'''

'Python List:\nDefinition: A built-in Python data structure that can hold a collection of items of different types.\nFlexibility: Lists can contain different data types, such as integers, strings, and other objects.\nNumPy Array:\nDefinition: A powerful, multidimensional array object provided by the NumPy library, designed for numerical computations.\nHomogeneity: NumPy arrays are homogeneous, meaning all elements must be of the same type (e.g., all integers or all floats).'

In [8]:
# 3. Find the shape, size and dimension of the following array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]


import numpy as np


array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])



print(array.shape , array.ndim)

(3, 4) 2


In [9]:
# 4. Write python code to access the first row of the following array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]] 

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

first_row = array[0]

print("First row:", first_row)


First row: [1 2 3 4]


In [10]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]  

# NAS

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

element = array[2, 3]

print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


In [11]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]] 

# ans


array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])



odd_indexed_elements = array[:, 1::2]

print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [12]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?  

# ans 

import numpy as np


random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)


Random 3x3 matrix with values between 0 and 1:
[[0.07792406 0.74968581 0.04126375]
 [0.28145324 0.57365204 0.96765162]
 [0.8165516  0.50389764 0.64119539]]


In [13]:
# 8. Describe the difference between np.random.rand and np.random.randn?

# ans

import numpy as np


uniform_random_matrix = np.random.rand(3, 3)

print("Uniform random matrix:")
print(uniform_random_matrix)


Uniform random matrix:
[[0.24437465 0.22703841 0.65395412]
 [0.96664165 0.69279314 0.41128119]
 [0.15997418 0.99471811 0.87793869]]


In [15]:
# Write code to increase the dimension of the following array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]] 

# ans

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


expanded_array = np.expand_dims(array, axis=0)

print("Array with an added dimension (axis=0):")
print(expanded_array)
print("Shape:", expanded_array.shape)


Array with an added dimension (axis=0):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Shape: (1, 3, 4)


In [16]:
# 10. How to transpose the following array in NumPy?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]] 

# ans

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

transposed_array = np.transpose(array)

print("Transposed array using np.transpose():")
print(transposed_array)

Transposed array using np.transpose():
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [19]:
'''11. Consider the following matrix:  Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]  Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]   
Perform the following operation using Python 
Index wise multiplicatio
Matrix multiplicatio
Add both the matric 
Subtract matrix B from a Divide Matrix B by A'''

# ans 

import numpy as np

# Define matrices A and B
matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

result = matrix_A * matrix_B

print("Element-wise multiplication result:")
print(result)

matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

result = np.dot(matrix_A, matrix_B.T)

print("Matrix multiplication result:")
print(result)


matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

result = matrix_A + matrix_B

print("Matrix addition result:")
print(result)

matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
result = matrix_A - matrix_B

print("Matrix subtraction result:")
print(result)

Element-wise multiplication result:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication result:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Matrix addition result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Matrix subtraction result:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
'''12. Which function in Numpy can be used to swap the byte order of an array?  13. What is the significance of the np.linalg.inv function?  14. What does the np.reshape function do, and how is it used?  15. What is broadcasting in Numpy?  '''

# /ans 

# The function used to swap the byte order of an array in NumPy is np.ndarray.byteswap().

# The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix.

# The np.reshape function in NumPy changes the shape of an array without changing its data.

'''Broadcasting is a set of rules in NumPy that allows arrays of different shapes to be used together in arithmetic operations. It provides a way to perform element-wise operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger array.'''

